
export const diffType = {
  NODE_DELETE: 'NODE_DELETE',
  NODE_TEXT_MODIFY: 'NODE_TEXT_MODIFY',
  NODE_REPLACE: 'NODE_REPLACE',
  NODE_ADD: 'NODE_ADD',
  NODE_ATTRIBUTE_MODIFY: 'NODE_ATTRIBUTE_MODIFY',
  NODE_ATTRIBUTE_ADD: 'NODE_ATTRIBUTE_ADD',
  NODE_ATTRIBUTE_DELETE: 'NODE_ATTRIBUTE_DELETE'
}
